name: Python Script

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - '**.py'
      - '**.css'
      - '**.html'
      - '**.js'
      - '!.github/**'
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get Lines of Code with CLOC.py
        run: python .github/workflows/CLOC.py

      # - uses: stefanzweifel/git-auto-commit-action@v4.16.0
      
      #### HEY it still can write even if there's no change, you need to address this

      - name: Commit README.md
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add README.md
          git commit -F README.md || echo "No changes to commit"
          git push

