name: Unittesting

on:
    push:
        paths:
            - '**.py'
        branches: ["main"]
    
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Unittesting
              run: python test_yt_downloader.py